In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [111]:
df = pd.read_csv('./sample_data_feb_2018.csv')

In [112]:
df = pd.read_csv('./sample_data_feb_2018.csv')

df1 = pd.read_csv('./sample_data_mar_2018.csv')

In [113]:
df = pd.concat([df, df1])

In [130]:
df['departure_date'] = pd.to_datetime(df['departure_date'])
df['departure_scheduled_time'] = pd.to_datetime(df['departure_scheduled_time'], unit='s')
df['departure_actual_time'] = pd.to_datetime(df['departure_actual_time'], unit='s')
df['arrival_scheduled_time'] = pd.to_datetime(df['arrival_scheduled_time'], unit='s')
df['arrival_actual_time'] = pd.to_datetime(df['arrival_actual_time'], unit='s')

In [185]:
df.dropna(inplace=True)
df.head()

,departure_date,airline_code,flight_number,source_airport,destination_airport,departure_scheduled_time,departure_actual_time,arrival_scheduled_time,arrival_actual_time,arrival_delta_minutes,...,departure_actual_time_month_of_year,departure_actual_time_year,arrival_scheduled_time_day_of_week,arrival_scheduled_time_day,arrival_scheduled_time_month_of_year,arrival_scheduled_time_year,arrival_actual_time_day_of_week,arrival_actual_time_day,arrival_actual_time_month_of_year,arrival_actual_time_year
0,2018-02-01,EK,5010,LHR,DXB,2018-02-01 11:55:00,2018-02-01 12:01:00,2018-02-01 19:05:00,2018-02-01 18:48:00,-17.0,...,2,2018,3,1,2,2018,3,1,2,2018
1,2018-02-01,IB,4649,LHR,BWI,2018-02-01 15:15:00,2018-02-01 15:29:00,2018-02-01 23:30:00,2018-02-02 00:02:00,32.0,...,2,2018,3,1,2,2018,4,2,2,2018
2,2018-02-01,NZ,4292,LHR,AUH,2018-02-01 09:00:00,2018-02-01 09:04:00,2018-02-01 16:25:00,2018-02-01 15:48:00,-37.0,...,2,2018,3,1,2,2018,3,1,2,2018
3,2018-02-01,KE,503,LHR,CDG,2018-02-01 20:10:00,2018-02-01 20:27:00,2018-02-01 21:35:00,2018-02-01 21:39:00,4.0,...,2,2018,3,1,2,2018,3,1,2,2018
4,2018-02-01,JJ,2861,LHR,GVA,2018-02-01 17:05:00,2018-02-01 17:01:00,2018-02-01 18:50:00,2018-02-01 18:37:00,-13.0,...,2,2018,3,1,2,2018,3,1,2,2018

In [121]:
unique_flights = df.groupby('airline_code')['flight_number'].nunique()
unique_flights.head()

airline_code
4U     12
9W     17
A3     12
AA    339
AC     76
Name: flight_number, dtype: int64

In [142]:
df[(df['flight_status'] != "LANDED")]

Empty DataFrame
Columns: [departure_date, airline_code, flight_number, source_airport, destination_airport, flight_status, departure_scheduled_time, departure_actual_time, arrival_scheduled_time, arrival_actual_time]
Index: []

In [143]:
df.drop(['flight_status'], axis=1, inplace=True)

In [192]:
df.dtypes

departure_date                            datetime64[ns]
airline_code                                    category
flight_number                                   category
source_airport                                  category
destination_airport                             category
departure_scheduled_time                  datetime64[ns]
departure_actual_time                     datetime64[ns]
arrival_scheduled_time                    datetime64[ns]
arrival_actual_time                       datetime64[ns]
arrival_delta_minutes                            float64
departure_date_day_of_week                         int64
departure_date_day_of_month                        int64
departure_date_month_of_year                       int64
departure_date_year                                int64
departure_scheduled_time_day_of_week               int64
departure_scheduled_time_day                       int64
departure_scheduled_time_month_of_year             int64
departure_scheduled_time_year                      int64
departure_actual_time_day_of_week                  int64
departure_actual_time_day                          int64
departure_actual_time_month_of_year                int64
departure_actual_time_year                         int64
arrival_scheduled_time_day_of_week                 int64
arrival_scheduled_time_day                         int64
arrival_scheduled_time_month_of_year               int64
arrival_scheduled_time_year                        int64
arrival_actual_time_day_of_week                    int64
arrival_actual_time_day                            int64
arrival_actual_time_month_of_year                  int64
arrival_actual_time_year                           int64
dtype: object

In [158]:
df['departure_date_day_of_week']=df.departure_date.dt.dayofweek
df['departure_date_day_of_month']=df.departure_date.dt.day
df['departure_date_month_of_year']=df.departure_date.dt.month
df['departure_date_year']=df.departure_date.dt.year

In [160]:
df['departure_scheduled_time_day_of_week']=df.departure_scheduled_time.dt.dayofweek
df['departure_scheduled_time_day']=df.departure_scheduled_time.dt.day
df['departure_scheduled_time_month_of_year']=df.departure_scheduled_time.dt.month
df['departure_scheduled_time_year']=df.departure_scheduled_time.dt.year

df['departure_actual_time_day_of_week']=df.departure_actual_time.dt.dayofweek
df['departure_actual_time_day']=df.departure_actual_time.dt.day
df['departure_actual_time_month_of_year']=df.departure_actual_time.dt.month
df['departure_actual_time_year']=df.departure_actual_time.dt.year

df['arrival_scheduled_time_day_of_week']=df.arrival_scheduled_time.dt.dayofweek
df['arrival_scheduled_time_day']=df.arrival_scheduled_time.dt.day
df['arrival_scheduled_time_month_of_year']=df.arrival_scheduled_time.dt.month
df['arrival_scheduled_time_year']=df.arrival_scheduled_time.dt.year

df['arrival_actual_time_day_of_week']=df.arrival_actual_time.dt.dayofweek
df['arrival_actual_time_day']=df.arrival_actual_time.dt.day
df['arrival_actual_time_month_of_year']=df.arrival_actual_time.dt.month
df['arrival_actual_time_year']=df.arrival_actual_time.dt.year

In [156]:
df['arrival_delta_minutes']=(df.arrival_actual_time-df.arrival_scheduled_time).astype('timedelta64[m]')

In [190]:
# airline_code flight_number source_airport destination_airport
df.airline_code = df.airline_code.astype('category')
df.flight_number = df.flight_number.astype('category')
df.source_airport = df.source_airport.astype('category')
df.destination_airport = df.destination_airport.astype('category')

In [191]:
df.memory_usage(deep = True)

Index                                     3426536
departure_date                             805096
airline_code                               111775
flight_number                              298946
source_airport                             100777
destination_airport                        217674
departure_scheduled_time                   805096
departure_actual_time                      805096
arrival_scheduled_time                     805096
arrival_actual_time                        805096
arrival_delta_minutes                      805096
departure_date_day_of_week                 805096
departure_date_day_of_month                805096
departure_date_month_of_year               805096
departure_date_year                        805096
departure_scheduled_time_day_of_week       805096
departure_scheduled_time_day               805096
departure_scheduled_time_month_of_year     805096
departure_scheduled_time_year              805096
departure_actual_time_day_of_week          805096
departure_actual_time_day                  805096
departure_actual_time_month_of_year        805096
departure_actual_time_year                 805096
arrival_scheduled_time_day_of_week         805096
arrival_scheduled_time_day                 805096
arrival_scheduled_time_month_of_year       805096
arrival_scheduled_time_year                805096
arrival_actual_time_day_of_week            805096
arrival_actual_time_day                    805096
arrival_actual_time_month_of_year          805096
arrival_actual_time_year                   805096
dtype: int64

In [189]:
df['flight_number'].nunique()

1969

In [241]:
df.head()

,departure_date,airline_code,flight_number,source_airport,destination_airport,departure_scheduled_time,departure_actual_time,arrival_scheduled_time,arrival_actual_time,arrival_delta_minutes,...,departure_actual_time_year,arrival_scheduled_time_day_of_week,arrival_scheduled_time_day,arrival_scheduled_time_month_of_year,arrival_scheduled_time_year,arrival_actual_time_day_of_week,arrival_actual_time_day,arrival_actual_time_month_of_year,arrival_actual_time_year,delayed
0,2018-02-01,EK,5010,LHR,DXB,2018-02-01 11:55:00,2018-02-01 12:01:00,2018-02-01 19:05:00,2018-02-01 18:48:00,-17.0,...,2018,3,1,2,2018,3,1,2,2018,0
1,2018-02-01,IB,4649,LHR,BWI,2018-02-01 15:15:00,2018-02-01 15:29:00,2018-02-01 23:30:00,2018-02-02 00:02:00,32.0,...,2018,3,1,2,2018,4,2,2,2018,1
2,2018-02-01,NZ,4292,LHR,AUH,2018-02-01 09:00:00,2018-02-01 09:04:00,2018-02-01 16:25:00,2018-02-01 15:48:00,-37.0,...,2018,3,1,2,2018,3,1,2,2018,0
3,2018-02-01,KE,503,LHR,CDG,2018-02-01 20:10:00,2018-02-01 20:27:00,2018-02-01 21:35:00,2018-02-01 21:39:00,4.0,...,2018,3,1,2,2018,3,1,2,2018,0
4,2018-02-01,JJ,2861,LHR,GVA,2018-02-01 17:05:00,2018-02-01 17:01:00,2018-02-01 18:50:00,2018-02-01 18:37:00,-13.0,...,2018,3,1,2,2018,3,1,2,2018,0

In [264]:
X = df[['airline_code', 'destination_airport', 'flight_number',
        'departure_date_day_of_week',
        'departure_date_day_of_month', 'departure_date_month_of_year',
        'departure_date_year','departure_scheduled_time_day_of_week',
        'departure_scheduled_time_day', 'departure_scheduled_time_month_of_year',
        'departure_scheduled_time_year', 'departure_actual_time_day_of_week',
        'departure_actual_time_day', 'departure_actual_time_month_of_year',
        'departure_actual_time_year', 'arrival_scheduled_time_day_of_week',
        'arrival_scheduled_time_day', 'arrival_scheduled_time_month_of_year',
        'arrival_scheduled_time_year', 'arrival_actual_time_day_of_week',
        'arrival_actual_time_day', 'arrival_actual_time_month_of_year',
        'arrival_actual_time_year','arrival_delta_minutes'
       ]]

In [269]:
Y = df['delayed']

In [266]:
df['delayed'] = df['arrival_delta_minutes'] > 30

In [267]:
df.delayed = df.delayed.astype('int')

In [231]:
from sklearn.ensemble import RandomForestClassifier

In [232]:
clf = RandomForestClassifier()

In [234]:
from sklearn.model_selection import train_test_split

In [310]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.5, random_state=42)

In [311]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [312]:
clf.score(X_test, y_test)

0.999980126791073

In [298]:
X.dtypes

departure_date_day_of_week                  int64
departure_date_day_of_month                 int64
departure_date_month_of_year                int64
departure_date_year                         int64
departure_scheduled_time_day_of_week        int64
departure_scheduled_time_day                int64
departure_scheduled_time_month_of_year      int64
departure_scheduled_time_year               int64
departure_actual_time_day_of_week           int64
departure_actual_time_day                   int64
departure_actual_time_month_of_year         int64
departure_actual_time_year                  int64
arrival_scheduled_time_day_of_week          int64
arrival_scheduled_time_day                  int64
arrival_scheduled_time_month_of_year        int64
arrival_scheduled_time_year                 int64
arrival_actual_time_day_of_week             int64
arrival_actual_time_day                     int64
arrival_actual_time_month_of_year           int64
arrival_actual_time_year                    int64
arrival_delta_minutes                     float64
airline_code_4U                             uint8
airline_code_9W                             uint8
airline_code_A3                             uint8
airline_code_AA                             uint8
airline_code_AC                             uint8
airline_code_AD                             uint8
airline_code_AF                             uint8
airline_code_AH                             uint8
airline_code_AI                             uint8
                                           ...
flight_number_9900                          uint8
flight_number_9931                          uint8
flight_number_9941                          uint8
flight_number_9943                          uint8
flight_number_9944                          uint8
flight_number_9949                          uint8
flight_number_9967                          uint8
flight_number_9973                          uint8
flight_number_9980                          uint8
departure_date_day_of_week                  int64
departure_date_day_of_month                 int64
departure_date_month_of_year                int64
departure_date_year                         int64
departure_scheduled_time_day_of_week        int64
departure_scheduled_time_day                int64
departure_scheduled_time_month_of_year      int64
departure_scheduled_time_year               int64
departure_actual_time_day_of_week           int64
departure_actual_time_day                   int64
departure_actual_time_month_of_year         int64
departure_actual_time_year                  int64
arrival_scheduled_time_day_of_week          int64
arrival_scheduled_time_day                  int64
arrival_scheduled_time_month_of_year        int64
arrival_scheduled_time_year                 int64
arrival_actual_time_day_of_week             int64
arrival_actual_time_day                     int64
arrival_actual_time_month_of_year           int64
arrival_actual_time_year                    int64
arrival_delta_minutes                     float64
Length: 2301, dtype: object

In [280]:
one_hot = pd.get_dummies(X, columns=["airline_code", "destination_airport", "flight_number"], prefix=["airline_code", "destination_airport", "flight_number"])

In [289]:
X = pd.concat([one_hot,X], axis=1)

In [297]:
X.drop(['airline_code','destination_airport','flight_number'], inplace=True, axis=1)

In [290]:
X

,departure_date_day_of_week,departure_date_day_of_month,departure_date_month_of_year,departure_date_year,departure_scheduled_time_day_of_week,departure_scheduled_time_day,departure_scheduled_time_month_of_year,departure_scheduled_time_year,departure_actual_time_day_of_week,departure_actual_time_day,...,departure_actual_time_year,arrival_scheduled_time_day_of_week,arrival_scheduled_time_day,arrival_scheduled_time_month_of_year,arrival_scheduled_time_year,arrival_actual_time_day_of_week,arrival_actual_time_day,arrival_actual_time_month_of_year,arrival_actual_time_year,arrival_delta_minutes
0,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-17.0
1,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,4,2,2,2018,32.0
2,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-37.0
3,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,4.0
4,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-13.0
5,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,17.0
6,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-10.0
7,3,1,2,2018,3,1,2,2018,3,1,...,2018,4,2,2,2018,4,2,2,2018,-4.0
8,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,19.0
9,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,25.0
10,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,3.0
11,3,1,2,2018,3,1,2,2018,3,1,...,2018,4,2,2,2018,4,2,2,2018,5.0
12,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,30.0
13,3,1,2,2018,3,1,2,2018,3,1,...,2018,4,2,2,2018,4,2,2,2018,-1.0
14,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-15.0
15,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,11.0
16,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-3.0
17,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,17.0
18,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-10.0
19,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,0.0
20,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,0.0
21,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-8.0
22,3,1,2,2018,3,1,2,2018,3,1,...,2018,4,2,2,2018,4,2,2,2018,1.0
23,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,0.0
24,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,7.0
25,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,2.0
26,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-14.0
27,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,-3.0
28,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,23.0
29,3,1,2,2018,3,1,2,2018,3,1,...,2018,3,1,2,2018,3,1,2,2018,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55798,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,-10.0
55799,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,-29.0
55801,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,-25.0
55802,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,48.0
55803,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-7.0
55804,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,0.0
55805,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,14.0
55806,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-3.0
55807,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,8.0
55808,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,0.0
55809,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-7.0
55810,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-13.0
55811,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,5.0
55812,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-10.0
55813,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,3.0
55814,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,5.0
55815,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-17.0
55816,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,-1.0
55817,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,-28.0
55818,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-6.0
55819,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-13.0
55820,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,2.0
55821,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-25.0
55822,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-17.0
55823,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,6.0
55824,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,2.0
55825,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-1.0
55826,5,31,3,2018,5,31,3,2018,5,31,...,2018,6,1,4,2018,6,1,4,2018,28.0
55827,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,0.0
55828,5,31,3,2018,5,31,3,2018,5,31,...,2018,5,31,3,2018,5,31,3,2018,-5.0